# Colecciones

## Matriz

In [28]:
m <- matrix(nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [29]:
dim(m)

[1] 2 3

In [30]:
# se completa col por col de izq a der
m <- matrix(1:6, nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## Lista

In [31]:
lista <- list(Numeros = 1:5, Cadena = c("Hola", "Hola"), Matriz = matrix(1:6, nrow = 2, ncol = 3))
lista

$Numeros
[1] 1 2 3 4 5

$Cadena
[1] "Hola" "Hola"

$Matriz
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

In [32]:
# lista de listas
lista_1 <- list(lista, lista)
lista_1

[[1]]
[[1]]$Numeros
[1] 1 2 3 4 5

[[1]]$Cadena
[1] "Hola" "Hola"

[[1]]$Matriz
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


[[2]]
[[2]]$Numeros
[1] 1 2 3 4 5

[[2]]$Cadena
[1] "Hola" "Hola"

[[2]]$Matriz
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

In [33]:
lista <- list("a", "b", "c")
lista

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

In [34]:
lista[1] <- "d"
lista

[[1]]
[1] "d"

[[2]]
[1] "b"

[[3]]
[1] "c"

In [35]:
length(lista)

[1] 3

In [36]:
"a" %in% lista

[1] FALSE

In [37]:
append(lista, "e")

[[1]]
[1] "d"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] "e"

In [38]:
append(lista, "z", after = 2)

[[1]]
[1] "d"

[[2]]
[1] "b"

[[3]]
[1] "z"

[[4]]
[1] "c"

In [39]:
lista <- lista[-1]
lista

[[1]]
[1] "b"

[[2]]
[1] "c"

In [40]:
# primer objeto
lista[1]              

[[1]]
[1] "b"

In [41]:
# primer elemento del primer objeto
lista[[1]][1]

[1] "b"

In [42]:
# del tercer objeto de la lista (matriz), extraemos el elemento ubicado en la fila 2, columna 3
lista[[3]][2, 3]

ERROR: Error in lista[[3]]: subscript out of bounds


In [43]:
# todos los objetos menos el último
lista[-length(lista)]
lista

[[1]]
[1] "b"

[[1]]
[1] "b"

[[2]]
[1] "c"

## Dataframe

In [72]:
df <- data.frame(fruta = c("manzana", "pera", "banana", "ciruela"), cant = 1:4)
df

fruta   cant
1 manzana 1   
2 pera    2   
3 banana  3   
4 ciruela 4

In [73]:
# número de filas
nrow(df)

[1] 4

In [74]:
# número de columnas
ncol(df)      

[1] 2

In [75]:
# nombres de las columnas
colnames(df)  

[1] "fruta" "cant"

In [76]:
# nombres de las filas
row.names(df)

[1] "1" "2" "3" "4"

In [ ]:
attributes(df)

In [77]:
df[1]

fruta  
1 manzana
2 pera   
3 banana 
4 ciruela

In [78]:
df[["fruta"]]

[1] "manzana" "pera"    "banana"  "ciruela"

In [79]:
df$fruta

[1] "manzana" "pera"    "banana"  "ciruela"

In [80]:
# nueva fila
df <- rbind(df, c("anana", 5))
df

fruta   cant
1 manzana 1   
2 pera    2   
3 banana  3   
4 ciruela 4   
5 anana   5

In [81]:
# nueva columna
df <- cbind(df, calorias = c(10, 60, 20, 10, 20))
df

fruta   cant calorias
1 manzana 1    10      
2 pera    2    60      
3 banana  3    20      
4 ciruela 4    10      
5 anana   5    20

In [82]:
# dato de la fila 1 y columna 1
df[1,1]

[1] "manzana"

In [83]:
# todos los datos de la fila 1
df[1, ]

fruta   cant calorias
1 manzana 1    10

In [84]:
# todos los datos de la columna 1
df[,1]

[1] "manzana" "pera"    "banana"  "ciruela" "anana"

In [85]:
# otra manera, todos los datos de la columna 1 
df[1]

fruta  
1 manzana
2 pera   
3 banana 
4 ciruela
5 anana

In [86]:
# otra manera, todos los datos de la columna 1 como vector
df[[1]]

[1] "manzana" "pera"    "banana"  "ciruela" "anana"

In [89]:
# otra manera, todos los datos de la columna 1 como vector
df$fruta

[1] "manzana" "pera"    "banana"  "ciruela" "anana"

In [91]:
iris_setosa <- subset(iris, Species=="setosa")
iris_setosa

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  5.1          3.5         1.4          0.2         setosa 
2  4.9          3.0         1.4          0.2         setosa 
3  4.7          3.2         1.3          0.2         setosa 
4  4.6          3.1         1.5          0.2         setosa 
5  5.0          3.6         1.4          0.2         setosa 
6  5.4          3.9         1.7          0.4         setosa 
7  4.6          3.4         1.4          0.3         setosa 
8  5.0          3.4         1.5          0.2         setosa 
9  4.4          2.9         1.4          0.2         setosa 
10 4.9          3.1         1.5          0.1         setosa 
11 5.4          3.7         1.5          0.2         setosa 
12 4.8          3.4         1.6          0.2         setosa 
13 4.8          3.0         1.4          0.1         setosa 
14 4.3          3.0         1.1          0.1         setosa 
15 5.8          4.0         1.2          0.2         setosa 
16 5.7          4.4         1.5          0.4         setosa 
17 5.4          3.9         1.3          0.4         setosa 
18 5.1          3.5         1.4          0.3         setosa 
19 5.7          3.8         1.7          0.3         setosa 
20 5.1          3.8         1.5          0.3         setosa 
21 5.4          3.4         1.7          0.2         setosa 
22 5.1          3.7         1.5          0.4         setosa 
23 4.6          3.6         1.0          0.2         setosa 
24 5.1          3.3         1.7          0.5         setosa 
25 4.8          3.4         1.9          0.2         setosa 
26 5.0          3.0         1.6          0.2         setosa 
27 5.0          3.4         1.6          0.4         setosa 
28 5.2          3.5         1.5          0.2         setosa 
29 5.2          3.4         1.4          0.2         setosa 
30 4.7          3.2         1.6          0.2         setosa 
31 4.8          3.1         1.6          0.2         setosa 
32 5.4          3.4         1.5          0.4         setosa 
33 5.2          4.1         1.5          0.1         setosa 
34 5.5          4.2         1.4          0.2         setosa 
35 4.9          3.1         1.5          0.2         setosa 
36 5.0          3.2         1.2          0.2         setosa 
37 5.5          3.5         1.3          0.2         setosa 
38 4.9          3.6         1.4          0.1         setosa 
39 4.4          3.0         1.3          0.2         setosa 
40 5.1          3.4         1.5          0.2         setosa 
41 5.0          3.5         1.3          0.3         setosa 
42 4.5          2.3         1.3          0.3         setosa 
43 4.4          3.2         1.3          0.2         setosa 
44 5.0          3.5         1.6          0.6         setosa 
45 5.1          3.8         1.9          0.4         setosa 
46 4.8          3.0         1.4          0.3         setosa 
47 5.1          3.8         1.6          0.2         setosa 
48 4.6          3.2         1.4          0.2         setosa 
49 5.3          3.7         1.5          0.2         setosa 
50 5.0          3.3         1.4          0.2         setosa

In [92]:
# Filtramos a la variedad Species reteniendo solo las categorías “setosa” y “virginica”
iris_set.virginica <- subset(iris, Species %in% c("setosa", "virginica"))

In [93]:
# Podemos filtrar las longitudes de sepal mayores a 5, reteniendo las variables "Sepal.Length" y "Species"
iris_sepal <- subset(iris, Sepal.Length > 5, select = c("Sepal.Length", "Species"))

In [94]:
# Filtramos haciendo las dos acciones a la vez
iris2 <- subset(iris, Species %in% c("setosa", "virginica") & Sepal.Length > 5, select = c("Sepal.Length", "Species"))

## Ejercicios

Crear un dataframe con las siguientes variables:

* Sexo: "hombre", "mujer", "hombre", "hombre", "mujer", "mujer", "hombre", "mujer"
* Presión arterial: 119, 99, 102, 78, 78, 82, 96, 104
* Pulsos por minuto: 59, 89, 107, 76, 91, 64, 78, 92

Guardarlo en un objeto llamado "datos"

In [102]:
datos <- data.frame(Sexo = c("hombre", "mujer", "hombre", "hombre", "mujer", "mujer", "hombre", "mujer"),
                    Presión_arterial = c(119, 99, 102, 78, 78, 82, 96, 104), 
                    Pulsos_por_minuto = c(59, 89, 107, 76, 91, 64, 78, 92))
datos

Sexo   Presión_arterial Pulsos_por_minuto
1 hombre 119               59              
2 mujer   99               89              
3 hombre 102              107              
4 hombre  78               76              
5 mujer   78               91              
6 mujer   82               64              
7 hombre  96               78              
8 mujer  104               92

Visualizar todos los valores para el primer y cuarto individuo

In [103]:
x <- datos[c(1,4),]
x

Sexo   Presión_arterial Pulsos_por_minuto
1 hombre 119              59               
4 hombre  78              76

Repetir lo mismo pero solo para las últimas dos variables

In [104]:
x <- datos[c(1,4),c(2,3)]
x

Presión_arterial Pulsos_por_minuto
1 119              59               
4  78              76

Determinar si la primera mujer de la tabla tiene una presión arterial mayor a la de la segunda mujer

In [105]:
x <- subset(datos, Sexo=='mujer')[1,2] > subset(datos, Sexo=='mujer')[2,2]
x

[1] TRUE

Construir una nueva columna que cuente los pulsos pero por hora

In [106]:
datos <- cbind(datos, Pulsos_por_hora = c(datos[,3] * 60))
datos

Sexo   Presión_arterial Pulsos_por_minuto Pulsos_por_hora
1 hombre 119               59               3540           
2 mujer   99               89               5340           
3 hombre 102              107               6420           
4 hombre  78               76               4560           
5 mujer   78               91               5460           
6 mujer   82               64               3840           
7 hombre  96               78               4680           
8 mujer  104               92               5520

Seleccionar solo los hombres que tengan una presión arterial mayor a 100 y guardar la tabla en una variable "hombres_mayor100"

In [107]:
hombres_mayor100 <- subset(datos, Sexo=='hombre' & Presión_arterial > 100)
hombres_mayor100

Sexo   Presión_arterial Pulsos_por_minuto Pulsos_por_hora
1 hombre 119               59               3540           
3 hombre 102              107               6420

Con la función max() determinar el valor máximo de pulsos por minutos de las mujeres

In [109]:
max <- max(subset(datos, Sexo=='mujer')[3])
max

[1] 92